export const data = {
  data: {
    exCompanyUsers: [
      {
        id: '01FE2M1CK0WCGNGHY38C4N3DNW',
        email: 'root@app.zeroboard-dev.jp',
        name: 'Test user',
        role: 'ADMIN',
        accessibleAllHubs: true,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'NOCONDITION',
          inviteAt: null,
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '01HGS9VDHKWXXY2WFCFBXVEQGD',
          role: 'ADMIN',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9YJBB4ERZJRXS2D1V0KRB',
        email: 'wingfung.wan+hogehoge001@zeroboard.jp',
        name: 'ほげほげ',
        role: 'EDITOR',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:13:50+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9ZBQC1XFP45BDTZ0452RB',
        email: 'wingfung.wan+hogehoge002@zeroboard.jp',
        name: 'ほげほげ002',
        role: 'INPUTTER',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:14:16+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXBA0D456MC14FGEMNGQBCG8',
        email: 'wingfung.wan+hogehoge003@zeroboard.jp',
        name: 'ほげほげ003',
        role: 'INPUTTER',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'NOTLOGGEDIN',
          inviteAt: '2024-05-08T14:14:50+09:00',
          passwordSetupAt: '2024-05-08T14:10:09+09:00',
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '01HXBA5KWMZMVY3YJRJFR0DQ4T',
          role: 'READER',
          workflowRequestApprovalManage: true,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
    ],
  },
}
