export const data = {
  data: {
    exCompanyUsers: [
      {
        id: '01HXB9J11V20GWTBRF8TMG957W',
        email: 'wingfung.wan+hogehoge001@zeroboard.jp',
        name: 'ほげほげ001',
        role: 'ADMIN',
        accessibleAllHubs: true,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:06:59+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9K748ZCEPVWC17XTDY43E',
        email: 'wingfung.wan+hogehoge002@zeroboard.jp',
        name: 'ほげほげ002',
        role: 'EDITOR',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:07:38+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9KR3M9YZ73FJ4CMG0RTSR',
        email: 'wingfung.wan+hogehoge003@zeroboard.jp',
        name: 'ほげほげ03',
        role: 'INPUTTER',
        accessibleAllHubs: true,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'NOTLOGGEDIN',
          inviteAt: '2024-05-08T14:07:56+09:00',
          passwordSetupAt: '2024-05-08T14:10:09+09:00',
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9M8MQKNSNC1V8G382YKG0',
        email: 'wingfung.wan+hogehoge004@zeroboard.jp',
        name: 'ほげほげ004',
        role: 'READER',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:08:13+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
      {
        id: '01HXB9MS1FX4HVQHCEZ1KG84MD',
        email: 'wingfung.wan+hogehoge005@zeroboard.jp',
        name: 'ほげほげ005',
        role: 'READER',
        accessibleAllHubs: false,
        hubsCount: 0,
        isActive: true,
        isLightMode: false,
        companyUserHistory: {
          inviteStatus: 'PASSWORDNOTSETUP',
          inviteAt: '2024-05-08T14:08:29+09:00',
          passwordSetupAt: null,
          loginAt: null,
          __typename: 'CompanyUserHistory',
        },
        companyUserWorkflowSetting: null,
        companyGroupUserRole: {
          id: '',
          role: 'DEFAULT',
          workflowRequestApprovalManage: false,
          __typename: 'CompanyGroupUserRole',
        },
        __typename: 'ExCompanyUser',
      },
    ],
  },
}
