export const data = {
  data: {
    hubGhgActivityList: {
      hub: {
        id: '01H4QN9WETK7V47ND0QW81G2DT',
        name: '大岡山',
        companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
        __typename: 'Hub',
      },
      ghgActivities: [
        {
          id: '01HD9XQMG0RAWQGEY12M5XDXQX',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GS9MXN3BS44JE5SXGCX6K2XS',
          masterGhgActivityCalculationMethodID: '01GS9N8GX9SSJ9PQ3B2E1GK18V',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE3',
          category: 'CATEGORY1',
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '二輪自動車の購入（金額ベース）',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: 's123',
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 3.967926175,
          locationBasedTotalCo2EmissionResult: 3.967926175,
          displayOrder: 422,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-10-22T05:09:56+09:00',
          updatedAt: '2023-10-22T05:13:01+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 2,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01HD9XQMG0RAWQGEY12MN35GWJ',
              ghgActivityID: '01HD9XQMG0RAWQGEY12M5XDXQX',
              masterGhgActivityItemID: '01GS9N8GXFXMMSX6CZCNH558MF',
              name: '金額',
              amount: 1000000,
              unit: '円',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01HD9XQMG0RAWQGEY12RA5H4AX',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01HD9XQMG0RAWQGEY12M5XDXQX',
              masterGhgEmissionFactorID: '01GRQEJ5YZ6MBZZ0TMY8GE70K3',
              masterGhgEmissionFactor: {
                id: '01GRQEJ5YZ6MBZZ0TMY8GE70K3',
                masterGhgEmissionFactorDataSourceID:
                  '01GR0PAC2PD50C7XPHPZQC9FR8',
                masterGhgEmissionFactorDataSource: {
                  id: '01GR0PAC2PD50C7XPHPZQC9FR8',
                  name: 'サプライチェーン排出量',
                  startDate: null,
                  endDate: null,
                  displayOrder: 5,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '二輪自動車　生産者価格ベース',
                inputUnit: '円',
                factor: 0.000003967926175,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTR6F7MPXRC9RSSEGT1',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTR6F7MPXRC9RSSEGT1',
                  name: 'サプライチェーン排出量',
                  url: 'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
                  copyright: '環境省、経済産業省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '金額法で算定されるうえでの諸注意：購入物・サービスの費用において、販売者から購入者であるユーザー企業様へ輸送・配送される際の料金が合算されている場合、本排出係数を活用するにあたって、総費用を活動量として登録することはできません。総費用から輸送・配送分を除いた数値を活動量として登録してください。\n',
                factorType: 'NORMAL',
                displayOrder: 652,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GRQEJ5Z431QKVRQ4WX9GJA05',
                    masterGhgEmissionFactorID: '01GRQEJ5YZ6MBZZ0TMY8GE70K3',
                    name: '排出原単位',
                    factor: 0.000003967926175,
                    unit: 'tCO2-eq/円',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: '円',
              factor: 0.000003967926175,
              emissionFactorReferenceSourceName: 'サプライチェーン排出量',
              emissionFactorReferenceSourceUrl:
                'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
              emissionFactorReferenceSourceCopyright: 'サプライチェーン排出量',
              emissionFactorComment:
                '金額法で算定されるうえでの諸注意：購入物・サービスの費用において、販売者から購入者であるユーザー企業様へ輸送・配送される際の料金が合算されている場合、本排出係数を活用するにあたって、総費用を活動量として登録することはできません。総費用から輸送・配送分を除いた数値を活動量として登録してください。\n',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 3.967926175,
              co2EmissionResult: 3.967926175,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01HD9XQMG0RAWQGEY12S5TCHHZ',
                  ghgActivityEmissionID: '01HD9XQMG0RAWQGEY12RA5H4AX',
                  masterGhgEmissionFactorItemID: '01GRQEJ5Z431QKVRQ4WX9GJA05',
                  name: '排出原単位',
                  factor: 0.000003967926175,
                  unit: 'tCO2-eq/円',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [
            {
              id: '0001',
              tag: { id: 'z0001', companyID: '00088', name: '関東地方' },
              tagID: 'z0001',
            },
            {
              id: '0002',
              tag: { id: 'z0002', companyID: '00088', name: '関西地方' },
              tagID: 'z0002',
            },
          ],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: true,
        },
        {
          id: '01HD9XPQP4QFE1SD1TW2AYEEW7',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GVFF50KFJZSJD72PZ813WJ1K',
          masterGhgActivityCalculationMethodID: '01GVHPSG6H3TS9392HDDXJS7X0',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE1',
          category: null,
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '液化天然ガス（LNG） 石灰焼成炉',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 0,
          label: 'あいうえお',
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 330.0073052939754,
          locationBasedTotalCo2EmissionResult: 330.0073052939754,
          displayOrder: 1677,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-10-22T05:09:27+09:00',
          updatedAt: '2023-10-22T05:13:09+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 2,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01HD9XPQP4QFE1SD1TW40ZY2VN',
              ghgActivityID: '01HD9XPQP4QFE1SD1TW2AYEEW7',
              masterGhgActivityItemID: '01GVHPSG6N4Q7YDCF3V7ERWQYM',
              name: '（燃料種ごとに）燃料使用量',
              amount: 122,
              unit: 't',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01HD9XPQP4QFE1SD1TW4CVZ2D9',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01HD9XPQP4QFE1SD1TW2AYEEW7',
              masterGhgEmissionFactorID: '01GVCXDPQ9VW61CFF5Q0CC1AF0',
              masterGhgEmissionFactor: {
                id: '01GVCXDPQ9VW61CFF5Q0CC1AF0',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '液化天然ガス（LNG） 石灰焼成炉 CO2',
                inputUnit: 't',
                factor: 2.7027000002457,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '単位使用量当たりの発熱量に単位熱量当たりの排出量を掛け合わせることで、単位使用量あたりの排出量を算定することができます。各排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 1945,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVCXDPQ9VW61CFF5Q0FYZQFX',
                    masterGhgEmissionFactorID: '01GVCXDPQ9VW61CFF5Q0CC1AF0',
                    name: '単位使用量当たりの発熱量',
                    factor: 54.6,
                    unit: 'GJ/t',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                  {
                    id: '01GVCXDPQ9VW61CFF5Q0PSN6GM',
                    masterGhgEmissionFactorID: '01GVCXDPQ9VW61CFF5Q0CC1AF0',
                    name: '単位発熱量当たりの炭素排出量',
                    factor: 0.0135,
                    unit: 'tC/GJ',
                    displayOrder: 2,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                  {
                    id: '01GVCXDPQ9VW61CFF5Q1A3536H',
                    masterGhgEmissionFactorID: '01GVCXDPQ9VW61CFF5Q0CC1AF0',
                    name: '二酸化炭素換算値',
                    factor: 3.666666667,
                    unit: 'tCO2/tC',
                    displayOrder: 3,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 't',
              factor: 2.7027000002457,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '単位使用量当たりの発熱量に単位熱量当たりの排出量を掛け合わせることで、単位使用量あたりの排出量を算定することができます。各排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 329.7294000299754,
              co2EmissionResult: 329.7294000299754,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01HD9XPQP4QFE1SD1TW7295299',
                  ghgActivityEmissionID: '01HD9XPQP4QFE1SD1TW4CVZ2D9',
                  masterGhgEmissionFactorItemID: '01GVCXDPQ9VW61CFF5Q0FYZQFX',
                  name: '単位使用量当たりの発熱量',
                  factor: 54.6,
                  unit: 'GJ/t',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
                {
                  id: '01HD9XPQP4QFE1SD1TW8CMWC5C',
                  ghgActivityEmissionID: '01HD9XPQP4QFE1SD1TW4CVZ2D9',
                  masterGhgEmissionFactorItemID: '01GVCXDPQ9VW61CFF5Q0PSN6GM',
                  name: '単位発熱量当たりの炭素排出量',
                  factor: 0.0135,
                  unit: 'tC/GJ',
                  displayOrder: 2,
                  __typename: 'GhgActivityEmissionFactor',
                },
                {
                  id: '01HD9XPQP4QFE1SD1TWB09QCSX',
                  ghgActivityEmissionID: '01HD9XPQP4QFE1SD1TW4CVZ2D9',
                  masterGhgEmissionFactorItemID: '01GVCXDPQ9VW61CFF5Q1A3536H',
                  name: '二酸化炭素換算値',
                  factor: 3.666666667,
                  unit: 'tCO2/tC',
                  displayOrder: 3,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
            {
              id: '01HD9XPQP4QFE1SD1TWEXTYWKT',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01HD9XPQP4QFE1SD1TW2AYEEW7',
              masterGhgEmissionFactorID: '01GVCXDPQH7MNH8BWXZ775Y18M',
              masterGhgEmissionFactor: {
                id: '01GVCXDPQH7MNH8BWXZ775Y18M',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4V3ZN4NV2XPEXCAXTP',
                masterGhg: {
                  id: '01G78M0D4V3ZN4NV2XPEXCAXTP',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'N2O',
                  gwp: 298,
                  displayOrder: 3,
                  ghgCategory: 'N2O',
                  __typename: 'MasterGhg',
                },
                name: '液化天然ガス（LNG） 石灰焼成炉 N2O',
                inputUnit: 't',
                factor: 0.000007644,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '単位使用量当たりの発熱量に単位熱量当たりの排出量を掛け合わせることで、単位使用量あたりの排出量を算定することができます。各排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 1946,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVCXDPQH7MNH8BWXZ85PJVH2',
                    masterGhgEmissionFactorID: '01GVCXDPQH7MNH8BWXZ775Y18M',
                    name: '単位使用量当たりの発熱量',
                    factor: 54.6,
                    unit: 'GJ/t',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                  {
                    id: '01GVCXDPQH7MNH8BWXZ9F4JQMQ',
                    masterGhgEmissionFactorID: '01GVCXDPQH7MNH8BWXZ775Y18M',
                    name: '単位発熱量当たりの排出量',
                    factor: 0.00000014,
                    unit: 'tN2O/GJ',
                    displayOrder: 2,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4V3ZN4NV2XPEXCAXTP',
              masterGhg: {
                id: '01G78M0D4V3ZN4NV2XPEXCAXTP',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'N2O',
                gwp: 298,
                displayOrder: 3,
                ghgCategory: 'N2O',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 't',
              factor: 0.000007644,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '単位使用量当たりの発熱量に単位熱量当たりの排出量を掛け合わせることで、単位使用量あたりの排出量を算定することができます。各排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 298,
              emissionResult: 0.000932568,
              co2EmissionResult: 0.277905264,
              factorRemarks: null,
              displayOrder: 2,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01HD9XPQP4QFE1SD1TWH6D6BS3',
                  ghgActivityEmissionID: '01HD9XPQP4QFE1SD1TWEXTYWKT',
                  masterGhgEmissionFactorItemID: '01GVCXDPQH7MNH8BWXZ85PJVH2',
                  name: '単位使用量当たりの発熱量',
                  factor: 54.6,
                  unit: 'GJ/t',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
                {
                  id: '01HD9XPQP4QFE1SD1TWJB44DK7',
                  ghgActivityEmissionID: '01HD9XPQP4QFE1SD1TWEXTYWKT',
                  masterGhgEmissionFactorItemID: '01GVCXDPQH7MNH8BWXZ9F4JQMQ',
                  name: '単位発熱量当たりの排出量',
                  factor: 0.00000014,
                  unit: 'tN2O/GJ',
                  displayOrder: 2,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01HD9XN2FPDRGTXN34YKGZPC7V',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GVFF5G4H7FN0P6YJ20EKKDGM',
          masterGhgActivityCalculationMethodID: '01GVG7XW06722D23CQH039YAV1',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE1',
          category: null,
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '変圧器等電気機械器具の製造及び使用の開始におけるSF6の封入',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: '日本語漢字',
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 123120,
          locationBasedTotalCo2EmissionResult: 123120,
          displayOrder: 2796,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-10-22T05:08:33+09:00',
          updatedAt: '2023-10-22T05:13:18+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 2,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01HD9XN2FPDRGTXN34YNRFTY88',
              ghgActivityID: '01HD9XN2FPDRGTXN34YKGZPC7V',
              masterGhgActivityItemID: '01GVHG2R0F5V2KMJPM5BEGRZZQ',
              name: '機器製造・使用開始時の使用量',
              amount: 200,
              unit: 'tSF6',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01HD9XN2FPDRGTXN34YS00BQA2',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01HD9XN2FPDRGTXN34YKGZPC7V',
              masterGhgEmissionFactorID: '01GVD3QA43YFRJ4GQFK561TC4Q',
              masterGhgEmissionFactor: {
                id: '01GVD3QA43YFRJ4GQFK561TC4Q',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4V6NYQQ1A1W3W4C85M',
                masterGhg: {
                  id: '01G78M0D4V6NYQQ1A1W3W4C85M',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'SF6',
                  gwp: 22800,
                  displayOrder: 33,
                  ghgCategory: 'SF6',
                  __typename: 'MasterGhg',
                },
                name: '変圧器等電気機械器具の製造及び使用の開始におけるSF6の封入',
                inputUnit: 'tSF6',
                factor: 0.027,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 3632,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVD3QA43YFRJ4GQFK6JFRFAF',
                    masterGhgEmissionFactorID: '01GVD3QA43YFRJ4GQFK561TC4Q',
                    name: '単位使用量当たりの排出量',
                    factor: 0.027,
                    unit: 'tSF6/tSF6',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4V6NYQQ1A1W3W4C85M',
              masterGhg: {
                id: '01G78M0D4V6NYQQ1A1W3W4C85M',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'SF6',
                gwp: 22800,
                displayOrder: 33,
                ghgCategory: 'SF6',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 'tSF6',
              factor: 0.027,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 22800,
              emissionResult: 5.4,
              co2EmissionResult: 123120,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01HD9XN2FPDRGTXN34YVJ6YE8X',
                  ghgActivityEmissionID: '01HD9XN2FPDRGTXN34YS00BQA2',
                  masterGhgEmissionFactorItemID: '01GVD3QA43YFRJ4GQFK6JFRFAF',
                  name: '単位使用量当たりの排出量',
                  factor: 0.027,
                  unit: 'tSF6/tSF6',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01HD9XM2NEHMZPTSKZG2ZXJBQ9',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GR0PJBHTRVTBE9YKTN6SQDKG',
          masterGhgActivityCalculationMethodID: '01GV7QQ4MM54PTNQKVFN4GHKA6',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE3',
          category: 'CATEGORY1',
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '米の購入（金額ベース）',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 0.016103671725,
          locationBasedTotalCo2EmissionResult: 0.016103671725,
          displayOrder: 1,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-10-22T05:08:00+09:00',
          updatedAt: '2023-10-22T05:08:51+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01HD9XM2NEHMZPTSKZG59M8G9X',
              ghgActivityID: '01HD9XM2NEHMZPTSKZG2ZXJBQ9',
              masterGhgActivityItemID: '01GV7QQ4MSXCFWKVZGNPX897T7',
              name: '金額',
              amount: 3000,
              unit: '円',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01HD9XM2NEHMZPTSKZG5JPAMKF',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01HD9XM2NEHMZPTSKZG2ZXJBQ9',
              masterGhgEmissionFactorID: '01GR0PGF26GQ5Z5TTBB5K707HY',
              masterGhgEmissionFactor: {
                id: '01GR0PGF26GQ5Z5TTBB5K707HY',
                masterGhgEmissionFactorDataSourceID:
                  '01GR0PAC2PD50C7XPHPZQC9FR8',
                masterGhgEmissionFactorDataSource: {
                  id: '01GR0PAC2PD50C7XPHPZQC9FR8',
                  name: 'サプライチェーン排出量',
                  startDate: null,
                  endDate: null,
                  displayOrder: 5,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '米　購入者価格ベース',
                inputUnit: '円',
                factor: 0.000005367890575,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTR6F7MPXRC9RSSEGT1',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTR6F7MPXRC9RSSEGT1',
                  name: 'サプライチェーン排出量',
                  url: 'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
                  copyright: '環境省、経済産業省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '金額法で算定されるうえでの諸注意：購入物・サービスの費用において、販売者から購入者であるユーザー企業様へ輸送・配送される際の料金が合算されている場合、本排出係数を活用するにあたって、総費用を活動量として登録することはできません。総費用から輸送・配送分を除いた数値を活動量として登録してください。',
                factorType: 'NORMAL',
                displayOrder: 2,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GRR6SVBBCPVDB9VWZK0APVJV',
                    masterGhgEmissionFactorID: '01GR0PGF26GQ5Z5TTBB5K707HY',
                    name: '排出原単位',
                    factor: 0.000005367890575,
                    unit: 'tCO2-eq/円',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: '円',
              factor: 0.000005367890575,
              emissionFactorReferenceSourceName: 'サプライチェーン排出量',
              emissionFactorReferenceSourceUrl:
                'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
              emissionFactorReferenceSourceCopyright: 'サプライチェーン排出量',
              emissionFactorComment:
                '金額法で算定されるうえでの諸注意：購入物・サービスの費用において、販売者から購入者であるユーザー企業様へ輸送・配送される際の料金が合算されている場合、本排出係数を活用するにあたって、総費用を活動量として登録することはできません。総費用から輸送・配送分を除いた数値を活動量として登録してください。',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 0.016103671725,
              co2EmissionResult: 0.016103671725,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01HD9XM2NEHMZPTSKZG6N4218D',
                  ghgActivityEmissionID: '01HD9XM2NEHMZPTSKZG5JPAMKF',
                  masterGhgEmissionFactorItemID: '01GRR6SVBBCPVDB9VWZK0APVJV',
                  name: '排出原単位',
                  factor: 0.000005367890575,
                  unit: 'tCO2-eq/円',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01H66312MZMVKHYE8VGFZWRY9N',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GVFF5GEABYTEFZ8A69A2SGZJ',
          masterGhgActivityCalculationMethodID: '01GVFRDE07P9AV0Z9GD2CHB6M2',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE2',
          category: null,
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '未利用熱の利用 産業用蒸気',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 0.78,
          locationBasedTotalCo2EmissionResult: 0.78,
          displayOrder: 2817,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-07-25T17:35:38+09:00',
          updatedAt: '2023-07-25T17:35:51+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01H66312MZMVKHYE8VGJN8B9XP',
              ghgActivityID: '01H66312MZMVKHYE8VGFZWRY9N',
              masterGhgActivityItemID: '01GVFRDE0B2PZGC2Q34HT61STB',
              name: '（熱の種類ごとに）熱使用量',
              amount: 13,
              unit: 'GJ',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01H66312MZMVKHYE8VGMMT1QMD',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01H66312MZMVKHYE8VGFZWRY9N',
              masterGhgEmissionFactorID: '01GVD3QA97RBPJ7Z4FZ25HN0GC',
              masterGhgEmissionFactor: {
                id: '01GVD3QA97RBPJ7Z4FZ25HN0GC',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '未利用熱の利用 産業用蒸気',
                inputUnit: 'GJ',
                factor: 0.06,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 3655,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVD3QA97RBPJ7Z4FZ2YZC6QN',
                    masterGhgEmissionFactorID: '01GVD3QA97RBPJ7Z4FZ25HN0GC',
                    name: '単位使用量当たりの排出量',
                    factor: 0.06,
                    unit: 'tCO2/GJ',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 'GJ',
              factor: 0.06,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 0.78,
              co2EmissionResult: 0.78,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01H66312MZMVKHYE8VGP5MF00M',
                  ghgActivityEmissionID: '01H66312MZMVKHYE8VGMMT1QMD',
                  masterGhgEmissionFactorItemID: '01GVD3QA97RBPJ7Z4FZ2YZC6QN',
                  name: '単位使用量当たりの排出量',
                  factor: 0.06,
                  unit: 'tCO2/GJ',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01H66312MEB26ZCR27AJ85Z2XF',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GVFF54A06CFXE4RMYWWE9Q4N',
          masterGhgActivityCalculationMethodID: '01GVG7XW06PKZ6QPNZK3GRHK10',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE1',
          category: null,
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: 'アンモニアの製造 液化石油ガス（LPG）',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 33,
          locationBasedTotalCo2EmissionResult: 33,
          displayOrder: 1941,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-07-25T17:35:38+09:00',
          updatedAt: '2023-07-25T17:35:52+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01H66312MEB26ZCR27AK7H0G80',
              ghgActivityID: '01H66312MEB26ZCR27AJ85Z2XF',
              masterGhgActivityItemID: '01GVHDE6NTYZ6F5NKYNVRRN8PM',
              name: '（原料種ごとに）原料使用量',
              amount: 11,
              unit: 't',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01H66312MEB26ZCR27AMDYR2CX',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01H66312MEB26ZCR27AJ85Z2XF',
              masterGhgEmissionFactorID: '01GVCZA64NF961EE5P1VZYV3CQ',
              masterGhgEmissionFactor: {
                id: '01GVCZA64NF961EE5P1VZYV3CQ',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: 'アンモニアの製造 液化石油ガス（LPG）',
                inputUnit: 't',
                factor: 3,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 2557,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVCZA64NF961EE5P1XK4Q8EP',
                    masterGhgEmissionFactorID: '01GVCZA64NF961EE5P1VZYV3CQ',
                    name: '単位使用量当たりの排出量',
                    factor: 3,
                    unit: 'tCO2/t',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 't',
              factor: 3,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 33,
              co2EmissionResult: 33,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01H66312MEB26ZCR27AMK83DDV',
                  ghgActivityEmissionID: '01H66312MEB26ZCR27AMDYR2CX',
                  masterGhgEmissionFactorItemID: '01GVCZA64NF961EE5P1XK4Q8EP',
                  name: '単位使用量当たりの排出量',
                  factor: 3,
                  unit: 'tCO2/t',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01H66312KQ3VTMHN6Q6KJMKN91',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GVFF549JKZQQMK221JJ0RHSX',
          masterGhgActivityCalculationMethodID: '01GVG7XW06X0VJKBZDC0JP8QE3',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE1',
          category: null,
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: 'アンモニアの製造 ナフサ',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 48.4,
          locationBasedTotalCo2EmissionResult: 48.4,
          displayOrder: 1940,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-07-25T17:35:38+09:00',
          updatedAt: '2023-07-25T17:35:54+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01H66312KQ3VTMHN6Q6MP2JRK6',
              ghgActivityID: '01H66312KQ3VTMHN6Q6KJMKN91',
              masterGhgActivityItemID: '01GVHDE6NTASNAJPKKG20750Q2',
              name: '（原料種ごとに）原料使用量',
              amount: 22,
              unit: 'kl',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01H66312KQ3VTMHN6Q6R73V16W',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01H66312KQ3VTMHN6Q6KJMKN91',
              masterGhgEmissionFactorID: '01GVCZA6492E3V79SDQQHAJFY0',
              masterGhgEmissionFactor: {
                id: '01GVCZA6492E3V79SDQQHAJFY0',
                masterGhgEmissionFactorDataSourceID:
                  '01GTZJD7AKMA6KZVCKEYWY76ZB',
                masterGhgEmissionFactorDataSource: {
                  id: '01GTZJD7AKMA6KZVCKEYWY76ZB',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  startDate: null,
                  endDate: null,
                  displayOrder: 3,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: 'アンモニアの製造 ナフサ',
                inputUnit: 'kl',
                factor: 2.2,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTRYH5Q2QB6PG3BXPBG',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTRYH5Q2QB6PG3BXPBG',
                  name: '算定・報告・公表制度における算定方法・排出係数一覧',
                  url: 'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
                  copyright: '環境省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
                factorType: 'NORMAL',
                displayOrder: 2556,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GVCZA6492E3V79SDQSYC08YS',
                    masterGhgEmissionFactorID: '01GVCZA6492E3V79SDQQHAJFY0',
                    name: '単位使用量当たりの排出量',
                    factor: 2.2,
                    unit: 'tCO2/kl',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: 'kl',
              factor: 2.2,
              emissionFactorReferenceSourceName:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorReferenceSourceUrl:
                'https://ghg-santeikohyo.env.go.jp/files/manual/chpt2_4-9_rev.pdf',
              emissionFactorReferenceSourceCopyright:
                '算定・報告・公表制度における算定方法・排出係数一覧',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 48.4,
              co2EmissionResult: 48.4,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01H66312KQ3VTMHN6Q6SRQHJ3A',
                  ghgActivityEmissionID: '01H66312KQ3VTMHN6Q6R73V16W',
                  masterGhgEmissionFactorItemID: '01GVCZA6492E3V79SDQSYC08YS',
                  name: '単位使用量当たりの排出量',
                  factor: 2.2,
                  unit: 'tCO2/kl',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01H66312K6VBD2R37KZHTQAARS',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GRX188KN8ZW2CHW0YR5WFDMQ',
          masterGhgActivityCalculationMethodID: '01GS7BNW7ZB6VTD9D1NEAHX724',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE3',
          category: 'CATEGORY2',
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '鉱業に関する資本財の購入 (石炭・原油・天然ガス)',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 0.007509574676,
          locationBasedTotalCo2EmissionResult: 0.007509574676,
          displayOrder: 590,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-07-25T17:35:38+09:00',
          updatedAt: '2023-07-25T17:36:02+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01H66312K6VBD2R37KZJPWAMWC',
              ghgActivityID: '01H66312K6VBD2R37KZHTQAARS',
              masterGhgActivityItemID: '01GS7BNW83N4G4JP3PKYCA3DVE',
              name: '金額',
              amount: 2000,
              unit: '円',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01H66312K6VBD2R37KZMKPMBAR',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01H66312K6VBD2R37KZHTQAARS',
              masterGhgEmissionFactorID: '01GRQWGGR472K9R97SMS02JDFA',
              masterGhgEmissionFactor: {
                id: '01GRQWGGR472K9R97SMS02JDFA',
                masterGhgEmissionFactorDataSourceID:
                  '01GR0PAC2PD50C7XPHPZQC9FR8',
                masterGhgEmissionFactorDataSource: {
                  id: '01GR0PAC2PD50C7XPHPZQC9FR8',
                  name: 'サプライチェーン排出量',
                  startDate: null,
                  endDate: null,
                  displayOrder: 5,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '鉱業　石炭・原油・天然ガス',
                inputUnit: '円',
                factor: 0.000003754787338,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTR6F7MPXRC9RSSEGT1',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTR6F7MPXRC9RSSEGT1',
                  name: 'サプライチェーン排出量',
                  url: 'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
                  copyright: '環境省、経済産業省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。\n',
                factorType: 'NORMAL',
                displayOrder: 907,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GRQWGGR9STXVEJJ6ND5TQB99',
                    masterGhgEmissionFactorID: '01GRQWGGR472K9R97SMS02JDFA',
                    name: '資本財価格当たり排出原単位',
                    factor: 0.000003754787338,
                    unit: 'tCO2-eq/円',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: '円',
              factor: 0.000003754787338,
              emissionFactorReferenceSourceName: 'サプライチェーン排出量',
              emissionFactorReferenceSourceUrl:
                'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
              emissionFactorReferenceSourceCopyright: 'サプライチェーン排出量',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。\n',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 0.007509574676,
              co2EmissionResult: 0.007509574676,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01H66312K6VBD2R37KZP16WGJD',
                  ghgActivityEmissionID: '01H66312K6VBD2R37KZMKPMBAR',
                  masterGhgEmissionFactorItemID: '01GRQWGGR9STXVEJJ6ND5TQB99',
                  name: '資本財価格当たり排出原単位',
                  factor: 0.000003754787338,
                  unit: 'tCO2-eq/円',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
        {
          id: '01H66312J9VA7DN78G4B3745AP',
          companyID: '01H4QMM4D25D893CBDMV6QR8TJ',
          hubID: '01H4QN9WETK7V47ND0QW81G2DT',
          activityID: null,
          ghgActivityCaseSettingID: null,
          ghgActivityCaseSetting: null,
          masterGhgActivityID: '01GRX188JD7DEDSMJXNDSKVFB4',
          masterGhgActivityCalculationMethodID: '01GS7AB6V7EP63Y140T3XTPW5C',
          masterGhgActivityFactorID: null,
          masterActivityType: null,
          scope: 'SCOPE3',
          category: 'CATEGORY2',
          startDate: '2023-07-01',
          endDate: '2023-07-31',
          name: '鉱業に関する資本財の購入 (分類不明)',
          calculationMethodType: 'EMISSION_FACTOR',
          operator: 1,
          label: null,
          ghgActivitySupplier: null,
          remarks: null,
          activityFactor: null,
          activityFactorReferenceSourceName: null,
          activityFactorReferenceSourceUrl: null,
          activityFactorReferenceSourceCopyright: null,
          activityFactorRemarks: null,
          totalCo2EmissionResult: 0.66801309624,
          locationBasedTotalCo2EmissionResult: 0.66801309624,
          displayOrder: 587,
          importedAt: null,
          tmpEmissionID: null,
          tmpMasterCalculationID: null,
          allowApplyWorkflowRequest: true,
          hasAccessRestrictionToMe: false,
          createdAt: '2023-07-25T17:35:38+09:00',
          updatedAt: '2023-07-25T17:36:09+09:00',
          creator: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          editor: {
            name: 'CSアカウント',
            __typename: 'CompanyUser',
          },
          revision: 1,
          ghgActivityTemplateBundleName: null,
          ghgActivityAmounts: [
            {
              id: '01H66312J9VA7DN78G4BEZK30N',
              ghgActivityID: '01H66312J9VA7DN78G4B3745AP',
              masterGhgActivityItemID: '01GS7AB6VBFYYEMZEAWHZBSKB3',
              name: '金額',
              amount: 180000,
              unit: '円',
              displayOrder: 0,
              __typename: 'GhgActivityAmount',
            },
          ],
          ghgActivityFactors: [],
          ghgActivityEmissions: [
            {
              id: '01H66312J9VA7DN78G4EQ89HWR',
              hubID: '01H4QN9WETK7V47ND0QW81G2DT',
              ghgActivityID: '01H66312J9VA7DN78G4B3745AP',
              masterGhgEmissionFactorID: '01GRQWEHHHPMR28FE7VR8K71PB',
              masterGhgEmissionFactor: {
                id: '01GRQWEHHHPMR28FE7VR8K71PB',
                masterGhgEmissionFactorDataSourceID:
                  '01GR0PAC2PD50C7XPHPZQC9FR8',
                masterGhgEmissionFactorDataSource: {
                  id: '01GR0PAC2PD50C7XPHPZQC9FR8',
                  name: 'サプライチェーン排出量',
                  startDate: null,
                  endDate: null,
                  displayOrder: 5,
                  __typename: 'MasterGhgEmissionFactorDataSource',
                },
                masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhg: {
                  id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                  masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                  name: 'CO2',
                  gwp: 1,
                  displayOrder: 1,
                  ghgCategory: 'CO2',
                  __typename: 'MasterGhg',
                },
                name: '鉱業　分類不明',
                inputUnit: '円',
                factor: 0.000003711183868,
                masterGhgEmissionFactorReferenceSourceID:
                  '01G78M0FTR6F7MPXRC9RSSEGT1',
                masterGhgEmissionFactorReferenceSource: {
                  id: '01G78M0FTR6F7MPXRC9RSSEGT1',
                  name: 'サプライチェーン排出量',
                  url: 'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
                  copyright: '環境省、経済産業省',
                  __typename: 'MasterGhgEmissionFactorReferenceSource',
                },
                emissionFactorComment:
                  '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。\n',
                factorType: 'NORMAL',
                displayOrder: 904,
                startDate: null,
                endDate: null,
                masterGhgEmissionFactorItems: [
                  {
                    id: '01GRQWEHHNREMFPXEDJNHSZBA9',
                    masterGhgEmissionFactorID: '01GRQWEHHHPMR28FE7VR8K71PB',
                    name: '資本財価格当たり排出原単位',
                    factor: 0.000003711183868,
                    unit: 'tCO2-eq/円',
                    displayOrder: 1,
                    __typename: 'MasterGhgEmissionFactorItem',
                  },
                ],
                basicEmissionFactorID: null,
                __typename: 'MasterGhgEmissionFactor',
              },
              companyGhgEmissionFactorID: null,
              companyGhgEmissionFactor: null,
              masterGhgID: '01G78M0D4VPNCQW5FFK0ZAP8F3',
              masterGhg: {
                id: '01G78M0D4VPNCQW5FFK0ZAP8F3',
                masterGhgVersionID: '01H3E77MGYR151ZH5DTEDEMWPS',
                name: 'CO2',
                gwp: 1,
                displayOrder: 1,
                ghgCategory: 'CO2',
                __typename: 'MasterGhg',
              },
              name: null,
              calculationMethodType: 'EMISSION_FACTOR',
              inputUnit: '円',
              factor: 0.000003711183868,
              emissionFactorReferenceSourceName: 'サプライチェーン排出量',
              emissionFactorReferenceSourceUrl:
                'https://www.env.go.jp/earth/ondanka/supply_chain/gvc/estimate.html#no04',
              emissionFactorReferenceSourceCopyright: 'サプライチェーン排出量',
              emissionFactorComment:
                '排出係数は、環境省が公表する平均値となりますが、実測値を登録されたい方は、上書きすることが可能です。\n',
              factorType: 'NORMAL',
              gwp: 1,
              emissionResult: 0.66801309624,
              co2EmissionResult: 0.66801309624,
              factorRemarks: null,
              displayOrder: 1,
              addedRowAt: null,
              hasAccessRestrictionToMe: false,
              ghgActivityEmissionFactors: [
                {
                  id: '01H66312J9VA7DN78G4FY2PCHG',
                  ghgActivityEmissionID: '01H66312J9VA7DN78G4EQ89HWR',
                  masterGhgEmissionFactorItemID: '01GRQWEHHNREMFPXEDJNHSZBA9',
                  name: '資本財価格当たり排出原単位',
                  factor: 0.000003711183868,
                  unit: 'tCO2-eq/円',
                  displayOrder: 1,
                  __typename: 'GhgActivityEmissionFactor',
                },
              ],
              __typename: 'GhgActivityEmission',
            },
          ],
          ghgActivityTags: [],
          ghgActivityOcr: null,
          requestAnswerGhgActivity: null,
          __typename: 'GhgActivity',
          ghgActivityAmountThresholdExceeded: null,
          hasGhgActivityAttachments: false,
        },
      ],
      __typename: 'HubGhgActivityList',
    },
  },
}
