// Generated by nuxt-og-image

declare module 'nitropack' {
  interface NitroRouteRules {
    ogImage?: false | import('../../../node_modules/.pnpm/nuxt-og-image@3.1.1_magicast@0.3.5_rollup@4.28.1_vite@5.4.11_@types+node@22.10.1_terser@5.37._2wtrrgbk7c5icwd34rsai7rxqe/node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions & Record<string, any>
  }
  interface NitroRouteConfig {
    ogImage?: false | import('../../../node_modules/.pnpm/nuxt-og-image@3.1.1_magicast@0.3.5_rollup@4.28.1_vite@5.4.11_@types+node@22.10.1_terser@5.37._2wtrrgbk7c5icwd34rsai7rxqe/node_modules/nuxt-og-image/dist/runtime/types').OgImageOptions & Record<string, any>
  }
  interface NitroRuntimeHooks {
    'nuxt-og-image:context': (ctx: import('../../../node_modules/.pnpm/nuxt-og-image@3.1.1_magicast@0.3.5_rollup@4.28.1_vite@5.4.11_@types+node@22.10.1_terser@5.37._2wtrrgbk7c5icwd34rsai7rxqe/node_modules/nuxt-og-image/dist/runtime/types').OgImageRenderEventContext) => void | Promise<void>
    'nuxt-og-image:satori:vnodes': (vnodes: import('../../../node_modules/.pnpm/nuxt-og-image@3.1.1_magicast@0.3.5_rollup@4.28.1_vite@5.4.11_@types+node@22.10.1_terser@5.37._2wtrrgbk7c5icwd34rsai7rxqe/node_modules/nuxt-og-image/dist/runtime/types').VNode, ctx: import('../../../node_modules/.pnpm/nuxt-og-image@3.1.1_magicast@0.3.5_rollup@4.28.1_vite@5.4.11_@types+node@22.10.1_terser@5.37._2wtrrgbk7c5icwd34rsai7rxqe/node_modules/nuxt-og-image/dist/runtime/types').OgImageRenderEventContext) => void | Promise<void>
  }
}

declare module '#og-image/components' {
  export interface OgImageComponents {
    'Docs': typeof import('../../..')['default']
    'BrandedLogo': typeof import('../../..')['default']
    'Frame': typeof import('../../..')['default']
    'Nuxt': typeof import('../../..')['default']
    'NuxtSeo': typeof import('../../..')['default']
    'Pergel': typeof import('../../..')['default']
    'SimpleBlog': typeof import('../../..')['default']
    'UnJs': typeof import('../../..')['default']
    'Wave': typeof import('../../..')['default']
    'WithEmoji': typeof import('../../..')['default']
  }
}
declare module '#og-image/unocss-config' {
  export type theme = any
}

export {}
