// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "../../app.config";
import type { default as appConfig1 } from "../../../node_modules/.pnpm/@nuxt+ui-pro@1.5.0_vue@3.5.13_typescript@5.6.3_/node_modules/@nuxt/ui-pro/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1]>

declare module "nitropack/types" {
  interface AppConfig extends UserAppConfig {}

}
export {}